### ISSUE TITLE
Support for pHAT

### ISSUE THREAD

**Issue by yucar** [sconemad/unicorn-scroller#2]
Hi!

Can you add support for Pimoroni Unicorn pHAT? (8x4 matrix)

Thanks, anyway this looks awesome :smh:

**Comment by sconemad** [comment]
I've just managed to get hold of a Unicorn pHAT, and I've added support for it. Obviously with the display being only 8x4, you only get to see quite a narrow slice of the text at a time, so I'm not sure it's all that great, but there you are.
